@hostdev = http://localhost:4002/api

###
GET {{hostdev}}/branchs
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MmZmM2VlOS1iODczLTRkN2YtODM1ZC1jZDg4MjgwMTA1ODIiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU0OTg4MzksImV4cCI6MTYwNTUzMTIzOX0.kdbqztH81UOFsog-ZHGkipP28N_3L2POVOZhM9yMJJM
Content-Type: application/json


