@mylocalhost = https://devcenter.heroku.com/categories/command-line/api

@mylocalhost = http://localhost:4002/api

###
GET {{mylocalhost}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTI2NTgsImV4cCI6MTYwNTU0NTA1OH0.OYqqe4g0CJRs1O7myPxUAZcyrSZ1r5PpT4KXLdz1JCo
Content-Type: application/json

###
GET {{mylocalhost}}/customers/1
Authorization: BearereyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTI2NTgsImV4cCI6MTYwNTU0NTA1OH0.OYqqe4g0CJRs1O7myPxUAZcyrSZ1r5PpT4KXLdz1JCo
Content-Type: application/json

###
GET {{mylocalhost}}/customers/branch/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTI2NTgsImV4cCI6MTYwNTU0NTA1OH0.OYqqe4g0CJRs1O7myPxUAZcyrSZ1r5PpT4KXLdz1JCo
Content-Type: application/json

###
POST {{mylocalhost}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU1MTI5NTIsImV4cCI6MTYwNTU0NTM1Mn0.Qpx1lDsWc3zgfs2sfOmPztFrXsz3wq_jjcZE-ws56is
Content-Type: application/json

{
    "name":"María Nájera",
    "address":"Sansare, Jalapa",
    "nit":"123456789",
    "contact":"Luis cisneros",
    "phone":"1231353",
    "branch_idbranch":"1"
}


