@mylocalhost = https://devcenter.heroku.com/categories/command-line/api

@mylocalhost = http://localhost:4002/api

###
GET {{mylocalhost}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTI2NTgsImV4cCI6MTYwNTU0NTA1OH0.OYqqe4g0CJRs1O7myPxUAZcyrSZ1r5PpT4KXLdz1JCo
Content-Type: application/json

###
GET {{mylocalhost}}/customers/1
Authorization: BearereyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTI2NTgsImV4cCI6MTYwNTU0NTA1OH0.OYqqe4g0CJRs1O7myPxUAZcyrSZ1r5PpT4KXLdz1JCo
Content-Type: application/json

###
GET {{mylocalhost}}/customers/branch/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTUyNjcsImV4cCI6MTYwNTU0NzY2N30.mCWYjDL-HmzU4dTis5RIyI14VL1xYcMJP6aLmEX8x78
Content-Type: application/json

###
POST {{mylocalhost}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTUyNjcsImV4cCI6MTYwNTU0NzY2N30.mCWYjDL-HmzU4dTis5RIyI14VL1xYcMJP6aLmEX8x78
Content-Type: application/json

{
    "name":"María Nájera 4",
    "address":"Sansare, Jalapa",
    "nit":"123456789",
    "contact":"Luis cisneros",
    "phone":"1231353",
    "branch_idbranch":"4"
}


