@hostdev = https://devcenter.heroku.com/categories/command-line/api

###
GET {{hostdev}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MmZmM2VlOS1iODczLTRkN2YtODM1ZC1jZDg4MjgwMTA1ODIiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU1MDA0NzEsImV4cCI6MTYwNTUzMjg3MX0.UEzIPdNPXKXl2vmFx-UPMxamvEDN3GPlbcO07JcL3wA
Content-Type: application/json

###
GET {{hostdev}}/customers/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MmZmM2VlOS1iODczLTRkN2YtODM1ZC1jZDg4MjgwMTA1ODIiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU1MDA0NzEsImV4cCI6MTYwNTUzMjg3MX0.UEzIPdNPXKXl2vmFx-UPMxamvEDN3GPlbcO07JcL3wA
Content-Type: application/json

###
GET {{hostdev}}/customers/branch/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMjA2MjU4Yi0yZjA5LTQ0MmUtYWE0NC0yOTc1NDk0MzdmYzEiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjozLCJpYXQiOjE2MDUxNTM5MTYsImV4cCI6MTYwNTE4NjMxNn0.d2-7Hd7qonpP8s1vBbOBjzqYIOOIKsv0B86_EEVWT0Q
Content-Type: application/json

###
POST {{hostdev}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMjA2MjU4Yi0yZjA5LTQ0MmUtYWE0NC0yOTc1NDk0MzdmYzEiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjozLCJpYXQiOjE2MDUxNTM5MTYsImV4cCI6MTYwNTE4NjMxNn0.d2-7Hd7qonpP8s1vBbOBjzqYIOOIKsv0B86_EEVWT0Q
Content-Type: application/json

{
    "name":"Jorge Bonilla",
    "address":"Sansare, Sanarate",
    "nit":"963258741",
    "contact":"Josue Trinidad",
    "phone":"75215985",
    "vendors_idvendor":"2",
    "branch_idbranch":"2"
}


